DROP SEQUENCE ID_GENERATOR_SEQ IF EXISTS;

CREATE SEQUENCE ID_GENERATOR_SEQ START WITH 0 INCREMENT BY 1;

DROP TABLE EMP IF EXISTS;
DROP TABLE DEPT IF EXISTS;




CREATE TABLE DEPT (
	ID 			NUMBER(5, 0),
	NAME		VARCHAR2(50),
	CONSTRAINT DEPT_PK PRIMARY KEY (ID)
);

CREATE TABLE EMP (
	ID 			NUMBER(10, 0),
	NAME		VARCHAR2(50),
	DEPT_ID 	NUMBER(5, 0),
	CONSTRAINT EMP_PK PRIMARY KEY (ID),
	CONSTRAINT EMP_FK FOREIGN KEY (DEPT_ID) REFERENCES DEPT (ID)
);

