DROP SEQUENCE REVISION_SEQ IF EXISTS;
CREATE SEQUENCE REVISION_SEQ START WITH 0  INCREMENT BY 1;

DROP TABLE REVISION_INFO IF EXISTS CASCADE;
CREATE TABLE REVISION_INFO (
	REVISION_ID 			NUMBER(10, 0),
	REVISION_TIMESTAMP		TIMESTAMP,
	CONSTRAINT REVISION_PK PRIMARY KEY (REVISION_ID)
);

DROP TABLE EMP_AUD IF EXISTS CASCADE;
DROP TABLE DEPT_AUD IF EXISTS CASCADE;


CREATE TABLE EMP_AUD(
	REV			NUMBER(10, 0),	
	REVTYPE		SMALLINT,
	ID			NUMBER(10, 0),
	NAME		VARCHAR2(50),
	DEPT_ID 	NUMBER(5, 0)
);

CREATE TABLE DEPT_AUD(
	REV			NUMBER(10, 0),	
	REVTYPE		SMALLINT,
	ID 			NUMBER(5, 0),
	NAME		VARCHAR2(50)
);

